package com.dvid.dcam.app.ui;

public enum MainScreen {
    LOGIN,
    CAMERA,
    MENU,
    FILES,
    RECORD_SETTINGS,
    VIDEO_STREAM_SETTINGS,
    GPS_SETTINGS,
    TRANSFER_SETTINGS,
    USER_SETTINGS,
    SERVER_SETTINGS,
    STORAGE_SETTINGS,
    DEVICE_SETTINGS,
    AUDIO_SETTINGS,
    CAMERA_SETTINGS,
    ABOUT,
    DEVELOPER_SETTINGS,
    DEVELOPER_BUTTON_BINDINGS,
    DEVELOPER_USERS
}
